.\" Manpage for seriousrunner
.\" Contact Alexander <t.x00100x.t@yandex.ru> to correct errors or typos.
.TH man 1 "09  2023" "1.0" "seriousrunner man page"
.SH NAME
seriousrunner - is open source program that loads and runs content created by users..
.SH SYNOPSIS
Open terminal and put command:
.TP
.B
seriousrunner
.TP
for start Serious Runner.
.SH DESCRIPTION
Serious Runner а small program that loads and runs content created by users for the game Serious Sam Classic. (Linux, FreeBSD).
.TP
.SH HOMEPAGE
https://github.com/tx00100xt/Serious-Runner
.TP
.SH AUTHOR
YAlexander <t.x00100x.t@yandex.ru>
