name: Build

env:
  QT_VERSION:     "5.15.2"
  MINGW_VERSION:  "win64_mingw61"
  MINGW_PATH:     ${{github.workspace}}\Qt\Tools\mingw810_64
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-alpine-64:
    name: Alpine ${{ matrix.Configuration }} ${{ matrix.Platform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Release]
        Platform: [x86_64]

    steps:
    - uses: actions/checkout@v3

    - name: Install latest stable Alpine Linux
      uses: jirutka/setup-alpine@master
      with:
        arch: ${{ matrix.Platform }}
        branch: 'latest-stable'
        packages: build-base cmake xz sed zlib-dev qt5-qtbase-dev libarchive-dev xz-dev

    - name: Get current date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
         format: "YYYYMMDD"

    - name: Show current date
      run: |
        echo "${{ steps.date.outputs.time }}"
 
    - name: Run Prepare
      shell: alpine.sh {0}
      run: |
          cd ${{github.workspace}}
          find . -name "CMakeLists.txt" -exec sed -i 's/-march=native/-mtune=generic/g' {} +
          mkdir x64 && mkdir x64/Serious-Runner && mkdir x64/Serious-Runner/DB
       
    - name: Run Build 
      shell: alpine.sh {0}
      run: |
          cd ${{github.workspace}}
          CFLAGS="-w" CXXFLAGS="-w" cmake -B ${{github.workspace}}/build-x64 -DCMAKE_BUILD_TYPE=${{ matrix.Configuration }}
          cd ${{github.workspace}}/build-x64
          make -j$(nproc || echo 4)
          cp -fr ${{github.workspace}}/build-x64/Serious-Runner ${{github.workspace}}/x64/Serious-Runner
          cp -fr ${{github.workspace}}/DB/seriousrunner.db ${{github.workspace}}/x64/Serious-Runner/DB
          cd ${{github.workspace}}
          tar -cJpvf Serious-Runner-${{ steps.date.outputs.time }}-alpine-x86_64-bin.tar.xz x64
          
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Serious-Runner-${{ steps.date.outputs.time }}-alpine-x86_64-bin.tar.xz
        path: Serious-Runner-${{ steps.date.outputs.time }}-alpine-x86_64-bin.tar.xz          

  build-ubuntu-x64:
    name: Ubuntu ${{ matrix.Configuration }} ${{ matrix.Platform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Release]
        Platform: [x64]

    steps:
    - uses: actions/checkout@v3

    - name: Install packages
      run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y qtbase5-dev libarchive-dev liblzma-dev &&
          sudo apt-get install -qq -y zlib1g-dev libxxhash-dev libarchive13  
          
    - name: Get current date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
         format: "YYYYMMDD"

    - name: Show current date
      run: |
        echo "${{ steps.date.outputs.time }}"         

    - name: Prepare
      run: |
          cd ${{github.workspace}}
          find . -name "CMakeLists.txt" -exec sed -i 's/-march=native/-mtune=generic/g' {} +
          mkdir {x64,x64/Serious-Runner,x64/Serious-Runner/DB}

    - name: Run Build
      run: |
          cd ${{github.workspace}}
          cmake -B ${{github.workspace}}/build-x64 -DCMAKE_BUILD_TYPE=${{ matrix.Configuration }}
          cd ${{github.workspace}}/build-x64
          make -j$(nproc || echo 4)
          cp -fr ${{github.workspace}}/build-x64/Serious-Runner ${{github.workspace}}/x64/Serious-Runner
          cp -fr ${{github.workspace}}/DB/seriousrunner.db ${{github.workspace}}/x64/Serious-Runner/DB
          cd ${{github.workspace}}
          tar -cJpvf Serious-Runner-${{ steps.date.outputs.time }}-lnx-amd64-bin.tar.xz x64

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Serious-Runner-${{ steps.date.outputs.time }}-lnx-amd64-bin.tar.xz
        path: Serious-Runner-${{ steps.date.outputs.time }}-lnx-amd64-bin.tar.xz 
  
  build-freebsd-x64:
    name: FreeBSD ${{ matrix.Configuration }} ${{ matrix.Platform }}
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Release]
        Platform: [x64]    
    steps:
      - uses: actions/checkout@v3

      - name: Get current date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYYMMDD"

      - name: Show current date
        run: |
          echo "${{ steps.date.outputs.time }}"
          
      - name: Build on FreeBSD
        uses: cross-platform-actions/action@v0.10.0
        with:
          operating_system: freebsd
          architecture: x86-64
          version: '13.1'
          shell: bash
          run: |
            uname -a
            sudo pkg install -y libarchive lzma zlib-ng cmake qt5
            cd ${{github.workspace}}
            mkdir {x64,x64/Serious-Runner,x64/Serious-Runner/DB}
            echo "*** Build ***"
            awk '{sub("-march=native","-mtune=generic")}1' CMakeLists.txt > CmakeTemp.txt && mv CmakeTemp.txt CMakeLists.txt
            cat CMakeLists.txt | grep mtune          
            cmake -B ${{github.workspace}}/build-x64 -DCMAKE_BUILD_TYPE=${{ matrix.Configuration }}
            cd ${{github.workspace}}/build-x64
            make -j$(sysctl -n hw.ncpu || echo 4)
         
            echo "*** Prepare Archive ***"            
            cd ${{github.workspace}}            
            cp -fr ${{github.workspace}}/build-x64/Serious-Runner ${{github.workspace}}/x64/Serious-Runner
            cp -fr ${{github.workspace}}/DB/seriousrunner.db ${{github.workspace}}/x64/Serious-Runner/DB
            echo "*** Create archive ***"
            XZ_DEFAULTS="-T 10" tar --use-compress-program=xz -cpvf Serious-Runner-${{ steps.date.outputs.time }}-bsd-amd64-bin.tar.xz x64
                      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Serious-Runner-${{ steps.date.outputs.time }}-bsd-amd64-bin.tar.xz
          path: Serious-Runner-${{ steps.date.outputs.time }}-bsd-amd64-bin.tar.xz
          
  build-windows-x64:
    name: Windows ${{ matrix.Configuration }} ${{ matrix.Platform }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Release]
        Platform: [x64]
    steps:
    - uses: actions/checkout@v3        
    - uses: suisei-cn/actions-download-file@v1.4.0
      id: downloadfile  # Remember to give an ID if you need the output filename
      name: Download the opensll 1.1.1v lib
      with:
        url: "https://archive.org/download/openssl-1.1.1v/1.1.1-22openssl_1.1.1v_prebuild_x64.7z"
        target: ${{github.workspace}}/Qt
        auto-match: false
        
    - name: Extract files
      run: | 
       cd ${{github.workspace}}\Qt
       7z x 1.1.1-22openssl_1.1.1v_prebuild_x64.7z
       cd ${{github.workspace}}\GnuWin
       copy GnuWin.zip "C:\Program Files"
       cd "C:\Program Files"
       7z x GnuWin.zip 
       
    - name: Get current date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
         format: "YYYYMMDD"

    - name: Show current date
      run: |
        echo "${{ steps.date.outputs.time }}"
 
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw81'
        dir: ${{github.workspace}}
        tools: 'tools_mingw,qt.tools.win64_mingw810 tools_ifw tools_cmake'
        archives: 'x86_64 qtxmlpatterns qtwinextras qttools qtscxml qtimageformats qtbase'
        set-env: 'true'

    - name: Qt 5 environment configuration
      shell: pwsh
      run: |
        Write-Output "${{ env.Qt5_DIR }}/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        Write-Output "${{ env.Qt5_DIR }}/../../Tools/mingw810_64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        
    - name: Set Parh
      run: |
        set PATH="%PATH%;${{github.workspace}}\Qt\Tools\mingw810_64\bin;${{github.workspace}}\Qt\Tools\QtInstallerFramework\4.6\bin"
                
    - name: Compiling
      run: |
       mkdir ${{github.workspace}}\build
       cd ${{github.workspace}}\build
       cmake -G "MinGW Makefiles" ..
       mingw32-make

    - name: Builing installer and portable archive      
      run: |
        echo *** Copy App ***
        copy ${{github.workspace}}\build\Serious-Runner.exe ${{github.workspace}}\Install\packages\org.seriousrunner.install\data\Serious-Runner
        cd ${{github.workspace}}\Install\packages\org.seriousrunner.install\data\Serious-Runner
        echo *** Deploy Serious-Runner ***
        windeployqt Serious-Runner.exe
        echo *** Copy DB ***
        mkdir ${{github.workspace}}\Install\packages\org.seriousrunner.install\data\Serious-Runner\DB
        copy ${{github.workspace}}\DB\seriousrunner.db ${{github.workspace}}\Install\packages\org.seriousrunner.install\data\Serious-Runner\DB        
        echo *** Copy libarhive ***
        copy "C:\Program Files\GnuWin32\bin\libarchive.dll" ${{github.workspace}}\Install\packages\org.seriousrunner.install\data\Serious-Runner
        copy "C:\Program Files\GnuWin32\bin\libzlib.dll" ${{github.workspace}}\Install\packages\org.seriousrunner.install\data\Serious-Runner
        copy "C:\Program Files\GnuWin32\bin\bz2-1.dll" ${{github.workspace}}\Install\packages\org.seriousrunner.install\data\Serious-Runner                
        echo *** Copy openssl libs ***
        copy ${{github.workspace}}\Qt\Tools\OpenSSL\Win_x64\bin\libcrypto-1_1-x64.dll ${{github.workspace}}\Install\packages\org.seriousrunner.install\data\Serious-Runner
        copy ${{github.workspace}}\Qt\Tools\OpenSSL\Win_x64/bin\libssl-1_1-x64.dll ${{github.workspace}}\Install\packages\org.seriousrunner.install\data\Serious-Runner        
        echo *** Copy Icon ***
        copy ${{github.workspace}}\Icons\seriousrunner.ico ${{github.workspace}}\Install\packages\org.seriousrunner.install\data\Serious-Runner\Serious-Runner.ico
        echo "*** Create installer ***"
        cd ${{github.workspace}}\Install        
        ${{github.workspace}}\Qt\Tools\QtInstallerFramework\4.6\bin\binarycreator.exe  -f -v -c "config/config.xml" -p "packages" "Serious-Runner-${{ steps.date.outputs.time }}-win64-Installer.exe"                
        copy Serious-Runner-${{ steps.date.outputs.time }}-win64-Installer.exe ${{github.workspace}}
        echo "*** Create archive ***"
        cd ${{github.workspace}}\Install\packages\org.seriousrunner.install\data        
        7z a -mx=9 Serious-Runner-${{ steps.date.outputs.time }}-win64-bin.7z Serious-Runner
        copy Serious-Runner-${{ steps.date.outputs.time }}-win64-bin.7z ${{github.workspace}}
        cd ${{github.workspace}}

    - name: Upload portable version
      uses: actions/upload-artifact@v3
      with:
        name: Serious-Runner-${{ steps.date.outputs.time }}-win64-bin.7z
        path: Serious-Runner-${{ steps.date.outputs.time }}-win64-bin.7z 

    - name: Upload installer version
      uses: actions/upload-artifact@v3
      with:
        name: Serious-Runner-${{ steps.date.outputs.time }}-win64-Installer.exe
        path: Serious-Runner-${{ steps.date.outputs.time }}-win64-Installer.exe      
